// Copyright (c) Microsoft Corporation
// The Microsoft Corporation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

namespace PowerAccent.Core.Services;

using Microsoft.PowerToys.Settings.UI.Library;
using Microsoft.PowerToys.Settings.UI.Library.Enumerations;
using Microsoft.PowerToys.Settings.UI.Library.Utilities;
using System.IO.Abstractions;
using System.Text.Json;

public class SettingsService
{
    private const string PowerAccentModuleName = "QuickAccent";
    private readonly ISettingsUtils _settingsUtils;
    private readonly IFileSystemWatcher _watcher;
    private readonly object _loadingSettingsLock = new object();

    public SettingsService()
    {
        _settingsUtils = new SettingsUtils();
        ReadSettings();
        _watcher = Helper.GetFileWatcher(PowerAccentModuleName, "settings.json", () => { ReadSettings(); });
    }

    private void ReadSettings()
    {
        // TODO this IO call should by Async, update GetFileWatcher helper to support async
        lock (_loadingSettingsLock)
        {
            {
                try
                {
                    if (!_settingsUtils.SettingsExists(PowerAccentModuleName))
                    {
                        Logger.LogInfo("QuickAccent settings.json was missing, creating a new one");
                        var defaultSettings = new PowerAccentSettings();
                        var options = new JsonSerializerOptions
                        {
                            WriteIndented = true,
                        };

                        _settingsUtils.SaveSettings(JsonSerializer.Serialize(this, options), PowerAccentModuleName);
                    }

                    var settings = _settingsUtils.GetSettingsOrDefault<PowerAccentSettings>(PowerAccentModuleName);
                    if (settings != null)
                    {
                        ActivationKey = settings.Properties.ActivationKey;
                        InputTime = settings.Properties.InputTime.Value;
                        switch (settings.Properties.ToolbarPosition.Value)
                        {
                            case "Top center":
                                Position = Position.Top;
                                break;
                            case "Bottom center":
                                Position = Position.Bottom;
                                break;
                            case "Left":
                                Position = Position.Left;
                                break;
                            case "Right":
                                Position = Position.Right;
                                break;
                            case "Top right corner":
                                Position = Position.TopRight;
                                break;
                            case "Top left corner":
                                Position = Position.TopLeft;
                                break;
                            case "Bottom right corner":
                                Position = Position.BottomRight;
                                break;
                            case "Bottom left corner":
                                Position = Position.BottomLeft;
                                break;
                            case "Center":
                                Position = Position.Center;
                                break;
                        }
                    }
                }
                catch (Exception ex)
                {
                    Logger.LogError("Failed to read changed settings", ex);
                }
            }
        }
    }

    private PowerAccentActivationKey _activationKey = PowerAccentActivationKey.Both;

    public PowerAccentActivationKey ActivationKey
    {
        get
        {
            return _activationKey;
        }

        set
        {
            _activationKey = value;
        }
    }

    private Position _position = Position.Top;

    public Position Position
    {
        get
        {
            return _position;
        }

        set
        {
            _position = value;
        }
    }

    private int _inputTime = 200;

    public int InputTime
    {
        get
        {
            return _inputTime;
        }

        set
        {
            _inputTime = value;
        }
    }

    public AccentPair[] GetLetterKey(LetterKey letter)
    {
        return GetDefaultLetterKey(letter);
    }

    public static AccentPair[] GetDefaultLetterKey(LetterKey letter)
    {
        switch (letter)
        {
            case LetterKey.A:
                return new AccentPair[]
                {
                    new("à", "À"),
                    new("â", "Â"),
                    new("á", "Á"),
                    new("ä", "Ä"),
                    new("ã", "Ã"),
                    new("å", "Å"),
                    new("ą", "Ą"),
                    new("ą́", "Ą́"),
                    new("ą̃", "Ą̃"),
                    new("ă", "Ă"),
                    new("ắ", "Ắ"),
                    new("ằ", "Ằ"),
                    new("ẵ", "Ẵ"),
                    new("ẳ", "Ẳ"),
                    new("ấ", "Ấ"),
                    new("ầ", "Ầ"),
                    new("ẫ", "Ẫ"),
                    new("ẩ", "Ẩ"),
                    new("ǎ", "Ǎ"),
                    new("ǻ", "Ǻ"),
                    new("ǟ", "Ǟ"),
                    new("ȧ", "Ȧ"),
                    new("ǡ", "Ǡ"),
                    new("ā", "Ā"),
                    new("ā̀", "Ā̀"),
                    new("ả", "Ả"),
                    new("ȁ", "Ȁ"),
                    new("a̋", "A̋"),
                    new("ȃ", "Ȃ"),
                    new("ạ", "Ạ"),
                    new("ặ", "Ặ"),
                    new("ậ", "Ậ"),
                    new("ḁ", "Ḁ"),
                    new("ą̈", "Ą̈"),
                    new("ⱥ", "Ⱥ"),
                    new("ẚ", "A͗"),
                    new("ā́", "Ā́"),
                    new("a̧", "A̧"),
                    new("a̭", "A̭"),
                    new("a̦", "A̦"),
                    new("a̱", "A̱"),
                    new("a̰", "A̰"),
                    new("ā̂", "Ā̂"),
                    new("ā̃", "Ā̃"),
                    new("ā̈", "Ā̈"),
                    new("å̄", "Å̄"),
                    new("ą̊", "Ą̊"),
                    new("å̂", "Å̂"),
                    new("å̃", "Å̃"),
                    new("å̆", "Å̆"),
                    new("ā̊", "Ā̊"),
                    new("å̱", "Å̱"),
                    new("ḁ̂", "Ḁ̂"),
                    new("a̍", "A̍"),
                    new("ɐ", "Ɐ"),
                    new("æ", "Æ"),
                    new("æ̨", "Æ̨"),
                    new("ᴂ", String.Empty),
                    new("ǣ", "Ǣ"),
                    new("ǽ", "Ǽ"),
                    new("æ̀", "Æ̀"),
                    new("ꜳ", "Ꜳ"),
                    new("ꜵ", "Ꜵ"),
                    new("ꜷ", "Ꜷ"),
                    new("ꜹ", "Ꜹ"),
                    new("ꜻ", "Ꜻ"),
                    new("ꜽ", "Ꜽ"),
                    new("ꬱ", String.Empty),
                    new("ꞛ", "Ꞛ"),
                    new("ꞻ", "Ꞻ"),
                    new(String.Empty, "ᴀ"),
                    new(String.Empty, "ᴁ"),
                    new("ᶏ", String.Empty),
                    new("₳", "₳"),
                    new("ａ", "Ａ"),
                };
            case LetterKey.B:
                return new AccentPair[]
                {
                    new("ḇ", "Ḇ"),
                    new("ḃ", "Ḃ"),
                    new("ḅ", "Ḅ"),
                    new("ƀ", "Ƀ"),
                    new("ɓ", "Ɓ"),
                    new("ꞗ", "Ꞗ"),
                    new("b́", "B́"),
                    new("b̆", "B̆"),
                    new("b̌", "B̌"),
                    new("b̧", "B̧"),
                    new("b̂", "B̂"),
                    new("b̭", "B̭"),
                    new("b̦", "B̦"),
                    new("b̈", "B̈"),
                    new("b̋", "B̋"),
                    new("b̏", "B̏"),
                    new("b̀", "B̀"),
                    new("b̉", "B̉"),
                    new("b̑", "B̑"),
                    new("b̄", "B̄"),
                    new("b̨", "B̨"),
                    new("b̊", "B̊"),
                    new("b̥", "B̥"),
                    new("b̃", "B̃"),
                    new("b̰", "B̰"),
                    new("ḇ̂", "Ḇ̂"),
                    new("b̵", "B̵"),
                    new("ƃ", "Ƃ"),
                    new("ƅ", "Ƅ"),
                    new(String.Empty, "ʙ"),
                    new(String.Empty, "ᴃ"),
                    new("ᵬ", String.Empty),
                    new("ᶀ", String.Empty),
                    new("␢", String.Empty),
                    new("฿", "฿"),
                    new("₿", "฿"),
                    new("ｂ", "Ｂ"),
                };
            case LetterKey.C:
                return new AccentPair[]
                {
                    new("ć", "Ć"),
                    new("ĉ", "Ĉ"),
                    new("č", "Č"),
                    new("ċ", "Ċ"),
                    new("ç", "Ç"),
                    new("ḉ", "Ḉ"),
                    new("c̨", "C̨"),
                    new("ȼ", "Ȼ"),
                    new("ꞓ", "Ꞓ"),
                    new("ꞔ", "Ꞔ"),
                    new("ƈ", "Ƈ"),
                    new("c̆", "C̆"),
                    new("c̭", "C̭"),
                    new("c̦", "C̦"),
                    new("c̈", "C̈"),
                    new("c̣", "C̣"),
                    new("c̋", "C̋"),
                    new("c̏", "C̏"),
                    new("c̀", "C̀"),
                    new("c̉", "C̉"),
                    new("c̑", "C̑"),
                    new("c̄", "C̄"),
                    new("c̱", "C̱"),
                    new("c̊", "C̊"),
                    new("c̥", "C̥"),
                    new("c̃", "C̃"),
                    new("c̰", "C̰"),
                    new("ć̣", "Ć̣"),
                    new("č̣", "Č̣"),
                    new("ç̇", "Ç̇"),
                    new('ꜿ', 'Ꜿ'),
                    new("ↄ", "Ↄ"),
                    new("ɕ", String.Empty),
                    new("ʗ", String.Empty),
                    new("𝼏", String.Empty),
                    new("𝼝", String.Empty),
                    new(String.Empty, "ᴄ"),
                    new("¢", "¢"),
                    new("₡", "₡"),
                    new("₢", "₢"),
                    new("₵", "₵"),
                    new("©", "©"),
                    new("ｃ", "Ｃ"),
                };
            case LetterKey.D:
                return new AccentPair[]
                {
                    new("ð", "Ð"),
                    new("ḏ", "Ḏ"),
                    new("ď", "Ď"),
                    new("ḋ", "Ḋ"),
                    new("ḑ", "Ḑ"),
                    new("d̦", "D̦"),
                    new("ḍ", "Ḍ"),
                    new("ḓ", "Ḓ"),
                    new("đ", "Đ"),
                    new("ɖ", "Ɖ"),
                    new("ꟈ", "Ꟈ"),
                    new("ɗ", "Ɗ"),
                    new("ꝺ", "Ꝺ"),
                    new("d́", "D́"),
                    new("d̆", "D̆"),
                    new("d̂", "D̂"),
                    new("d̈", "D̈"),
                    new("d̋", "D̋"),
                    new("d̏", "D̏"),
                    new("d̀", "D̀"),
                    new("d̉", "D̉"),
                    new("d̑", "D̑"),
                    new("d̄", "D̄"),
                    new("d̨", "D̨"),
                    new("d̊", "D̊"),
                    new("d̥", "D̥"),
                    new("d̃", "D̃"),
                    new("d̰", "D̰"),
                    new("ƌ", "Ƌ"),
                    new("ᵭ", String.Empty),
                    new("ᶁ", String.Empty),
                    new("ᶑ", String.Empty),
                    new("ȡ", String.Empty),
                    new("ꝱ", String.Empty),
                    new("𝼥", String.Empty),
                    new("ȸ", String.Empty),
                    new("ʣ", String.Empty),
                    new("ʥ", String.Empty),
                    new("ꭦ", String.Empty),
                    new("ʤ", String.Empty),
                    new("𝼙", String.Empty),
                    new("ǳ", "Ǳ"),
                    new(String.Empty, "ǲ"),
                    new("ǆ", "Ǆ"),
                    new(String.Empty, "ǅ"),
                    new(String.Empty, "ᴅ"),
                    new(String.Empty, "ᴆ"),
                    new("₫", "₫"),
                    new("ｄ", "Ｄ"),
                };
            case LetterKey.E:
                return new AccentPair[]
                {
                    new("é", "É"),
                    new("è", "È"),
                    new("ê", "Ê"),
                    new("ë", "Ë"),
                    new("ē", "Ē"),
                    new("ė", "Ė"),
                    new("ĕ", "Ĕ"),
                    new("ế", "Ế"),
                    new("ề", "Ề"),
                    new("ễ", "Ễ"),
                    new("ể", "Ể"),
                    new("ê̄", "Ê̄"),
                    new("ê̌", "Ê̌"),
                    new("ě", "Ě"),
                    new("ẽ", "Ẽ"),
                    new("ė́", "Ė́"),
                    new("ė̃", "Ė̃"),
                    new("ȩ", "Ȩ"),
                    new("ḝ", "Ḝ"),
                    new("ę", "Ę"),
                    new("ę́", "Ę́"),
                    new("ę̃", "Ę̃"),
                    new("ḗ", "Ḗ"),
                    new("ḕ", "Ḕ"),
                    new("ẻ", "Ẻ"),
                    new("ȅ", "Ȅ"),
                    new("e̋", "E̋"),
                    new("ȇ", "Ȇ"),
                    new("ẹ", "Ẹ"),
                    new("ệ", "Ệ"),
                    new("ḙ", "Ḙ"),
                    new("ḛ", "Ḛ"),
                    new("ɇ", "Ɇ"),
                    new("e̩", "E̩"),
                    new("è̩", "È̩"),
                    new("é̩", "É̩"),
                    new("ꝫ", "Ꝫ"),
                    new("ɛ", "Ɛ"),
                    new("ɜ", "Ɜ"),
                    new("e̦", "E̦"),
                    new("e̱", "E̱"),
                    new("e̊", "E̊"),
                    new("e̥", "E̥"),
                    new("ȩ̇", "Ȩ̇"),
                    new("ē̂", "Ē̂"),
                    new("ē̃", "Ē̃"),
                    new("ë̄", "Ë̄"),
                    new("e̊̄", "E̊̄"),
                    new("ǝ", "Ǝ"),
                    new("ə", "Ə"),
                    new("ɞ", String.Empty),
                    new("ɘ", String.Empty),
                    new("ɚ", String.Empty),
                    new("ʚ", String.Empty),
                    new("ᶒ", String.Empty),
                    new("ⱸ", String.Empty),
                    new("ꬴ", String.Empty),
                    new("ꬳ", String.Empty),
                    new("ɝ", String.Empty),
                    new(String.Empty, "ⱻ"),
                    new("ꬲ", String.Empty),
                    new(String.Empty, "ᴇ"),
                    new(String.Empty, "ᴈ"),
                    new("ᶓ", String.Empty),
                    new("ᶔ", String.Empty),
                    new("ᶕ", String.Empty),
                    new("€", "€"),
                    new("ｅ", "Ｅ"),
                };
            case LetterKey.F:
                return new AccentPair[]
                {
                    new("ḟ", "Ḟ"),
                    new("ƒ", "Ƒ"),
                    new("ꞙ", "Ꞙ"),
                    new("ꝼ", "Ꝼ"),
                    new("f́", "F́"),
                    new("f̆", "F̆"),
                    new("f̌", "F̌"),
                    new("f̧", "F̧"),
                    new("f̂", "F̂"),
                    new("f̭", "F̭"),
                    new("f̦", "F̦"),
                    new("f̈", "F̈"),
                    new("f̣", "F̣"),
                    new("f̋", "F̋"),
                    new("f̏", "F̏"),
                    new("f̀", "F̀"),
                    new("f̉", "F̉"),
                    new("f̑", "F̑"),
                    new("f̄", "F̄"),
                    new("f̱", "F̱"),
                    new("f̨", "F̨"),
                    new("f̊", "F̊"),
                    new("f̥", "F̥"),
                    new("f̃", "F̃"),
                    new("f̰", "F̰"),
                    new("ᵮ", String.Empty),
                    new("ᶂ", String.Empty),
                    new(String.Empty, "ꜰ"),
                    new(String.Empty, "ꟻ"),
                    new("ﬀ", String.Empty),
                    new("ﬁ", String.Empty),
                    new("ﬃ", String.Empty),
                    new("ﬂ", String.Empty),
                    new("ﬄ", String.Empty),
                    new("ʩ", String.Empty),
                    new("𝼀", String.Empty),
                    new("₣", "₣"),
                    new("ｆ", "Ｆ"),
                };
            case LetterKey.G:
                return new AccentPair[]
                {
                    new("ğ", "Ğ"),
                    new("ǧ", "Ǧ"),
                    new("ĝ", "Ĝ"),
                    new("ḡ", "Ḡ"),
                    new("ǵ", "Ǵ"),
                    new("ǥ", "Ǥ"),
                    new("ģ", "Ģ"),
                    new("ɠ", "Ɠ"),
                    new("ġ", "Ġ"),
                    new("ꞡ", "Ꞡ"),
                    new("g̃", "G̃"),
                    new("ᵹ", "Ᵹ"),
                    new("ꝿ", "Ꝿ"),
                    new("ꟑ", "Ꟑ"),
                    new("g̭", "G̭"),
                    new("g̦", "G̦"),
                    new("g̈", "G̈"),
                    new("g̣", "G̣"),
                    new("g̋", "G̋"),
                    new("g̏", "G̏"),
                    new("g̀", "G̀"),
                    new("g̉", "G̉"),
                    new("g̑", "G̑"),
                    new("g̱", "G̱"),
                    new("g̨", "G̨"),
                    new("g̊", "G̊"),
                    new("g̥", "G̥"),
                    new("g̰", "G̰"),
                    new("ƣ", "Ƣ"),
                    new("ɡ", "Ɡ"),
                    new(String.Empty, "ɢ"),
                    new(String.Empty, "ʛ"),
                    new("ꬶ", String.Empty),
                    new("ᶃ", String.Empty),
                    new("ᵷ", String.Empty),
                    new("𝼁", String.Empty),
                    new("𝼂", String.Empty),
                    new("₲", "₲"),
                    new("ｇ", "Ｇ"),
                };
            case LetterKey.H:
                return new AccentPair[]
                {
                    new("ḧ", "Ḧ"),
                    new("ḫ", "Ḫ"),
                    new("ḥ", "Ḥ"),
                    new("ĥ", "Ĥ"),
                    new("ȟ", "Ȟ"),
                    new("ḣ", "Ḣ"),
                    new("ḩ", "Ḩ"),
                    new("ẖ", "H̱"),
                    new("ħ", "Ħ"),
                    new("ⱨ", "Ⱨ"),
                    new("ɦ", "Ɦ"),
                    new("ꜧ", "Ꜧ"),
                    new("h́", "H́"),
                    new("h̆", "H̆"),
                    new("h̭", "H̭"),
                    new("h̦", "H̦"),
                    new("h̋", "H̋"),
                    new("h̏", "H̏"),
                    new("h̀", "H̀"),
                    new("h̉", "H̉"),
                    new("h̑", "H̑"),
                    new("h̄", "H̄"),
                    new("h̨", "H̨"),
                    new("h̊", "H̊"),
                    new("h̥", "H̥"),
                    new("h̃", "H̃"),
                    new("h̰", "H̰"),
                    new("ƕ", "Ƕ"),
                    new("ɥ", " Ɥ"),
                    new("ꞕ", String.Empty),
                    new("ɧ", String.Empty),
                    new("ʮ", String.Empty),
                    new("ʯ", String.Empty),
                    new(String.Empty, "ʜ"),
                    new(String.Empty, "Ⱶ"),
                    new(String.Empty, "Ꟶ"),
                    new("ｈ", "Ｈ"),
                };
            case LetterKey.I:
                return new AccentPair[]
                {
                    new("î", "Î"),
                    new("ï", "Ï"),
                    new("í", "Í"),
                    new("i̇̉", "İ̉"),
                    new("ì", "Ì"),
                    new("ī", "Ī"),
                    new("ı", String.Empty),
                    new("ĭ", "Ĭ"),
                    new("ḭ", "Ḭ"),
                    new("ỉ", "Ỉ"),
                    new("i̇́", "İ́"),
                    new("i̇̀", "İ̀"),
                    new("ǐ", "Ǐ"),
                    new("ḯ", "Ḯ"),
                    new("ĩ", "Ĩ"),
                    new("i̇̃", "İ̃"),
                    new("į", "Į"),
                    new("į̇́", "Į́"),
                    new("į̇̃", "Į̃"),
                    new("ī̀", "Ī̀"),
                    new("ȉ", "Ȉ"),
                    new("i̋", "I̋"),
                    new("ȋ", "Ȋ"),
                    new("ị", "Ị"),
                    new("ɨ", "Ɨ"),
                    new("ɨ̧", "Ɨ̧"),
                    new("i̧", "I̧"),
                    new("i̭", "I̭"),
                    new("i̦", "I̦"),
                    new("i̱", "I̱"),
                    new("i̊", "I̊"),
                    new("i̥", "I̥"),
                    new("ī́", "Ī́"),
                    new("ī̂", "Ī̂"),
                    new("ī̭", "Ī̭"),
                    new("ī̃", "Ī̃"),
                    new("į́", "Į́"),
                    new("į̃", "Į̃"),
                    new("ɪ", "Ɪ"),
                    new("ꞽ", "Ꞽ"),
                    new("ĳ", "Ĳ"),
                    new(String.Empty, "İ"),
                    new(String.Empty, "ꟷ"),
                    new(String.Empty, "ꟾ"),
                    new(String.Empty, "ᴉ"),
                    new("ᶖ", String.Empty),
                    new("𝼚", String.Empty),
                    new(String.Empty, "ᵻ"),
                    new("ｉ", "Ｉ"),
                };
            case LetterKey.J:
                return new AccentPair[]
                {
                    new("ĵ", "Ĵ"),
                    new("ɉ", "Ɉ"),
                    new("ǰ", "J̌"),
                    new("ʝ", "Ʝ"),
                    new("j̇̃", "J̃"),
                    new("j̨", "J̨"),
                    new("j́", "J́"),
                    new("j̆", "J̆"),
                    new("j̧", "J̧"),
                    new("j̭", "J̭"),
                    new("j̦", "J̦"),
                    new("j̈", "J̈"),
                    new("j̣", "J̣"),
                    new("j̋", "J̋"),
                    new("j̏", "J̏"),
                    new("j̀", "J̀"),
                    new("j̉", "J̉"),
                    new("j̑", "J̑"),
                    new("j̄", "J̄"),
                    new("j̱", "J̱"),
                    new("j̊", "J̊"),
                    new("j̥", "J̥"),
                    new("j̃", "J̃"),
                    new("j̰", "J̰"),
                    new(String.Empty, "J̇"),
                    new("j̃", String.Empty),
                    new("ɟ", String.Empty),
                    new("ʄ", String.Empty),
                    new("ȷ", String.Empty),
                    new(String.Empty, "ᴊ"),
                    new("ｊ", "Ｊ"),
                };
            case LetterKey.K:
                return new AccentPair[]
                {
                    new("ḵ", "Ḵ"),
                    new("ḳ", "Ḳ"),
                    new("ǩ", "Ǩ"),
                    new("ḱ", "Ḱ"),
                    new("ķ", "Ķ"),
                    new("ƙ", "Ƙ"),
                    new("ⱪ", "Ⱪ"),
                    new("ꝁ", "Ꝁ"),
                    new("ꝃ", "Ꝃ"),
                    new("ꝅ", "Ꝅ"),
                    new("ꞣ", "Ꞣ"),
                    new("k̆", "K̆"),
                    new("k̂", "K̂"),
                    new("k̭", "K̭"),
                    new("k̦", "K̦"),
                    new("k̈", "K̈"),
                    new("k̇", "K̇"),
                    new("k̋", "K̋"),
                    new("k̏", "K̏"),
                    new("k̀", "K̀"),
                    new("k̉", "K̉"),
                    new("k̑", "K̑"),
                    new("k̄", "K̄"),
                    new("k̨", "K̨"),
                    new("k̊", "K̊"),
                    new("k̥", "K̥"),
                    new("k̃", "K̃"),
                    new("k̰", "K̰"),
                    new("ʞ", "Ʞ"),
                    new("ᶄ", String.Empty),
                    new("𝼃", String.Empty),
                    new(String.Empty, "𝼐"),
                    new(String.Empty, "ᴋ"),
                    new("₭", "₭"),
                    new("ｋ", "Ｋ"),
                };
            case LetterKey.L:
                return new AccentPair[]
                {
                    new("ɫ", "Ɫ"),
                    new("ł", "Ł"),
                    new("ḻ", "Ḻ"),
                    new("ĺ", "Ĺ"),
                    new("ľ", "Ľ"),
                    new("ļ", "Ļ"),
                    new("ḷ", "Ḷ"),
                    new("ḹ", "Ḹ"),
                    new("l̃", "L̃"),
                    new("ḽ", "Ḽ"),
                    new("ŀ", "Ŀ"),
                    new("ƚ", "Ƚ"),
                    new("ꝉ", "Ꝉ"),
                    new("ⱡ", "Ⱡ"),
                    new("ɬ", "Ɬ"),
                    new("ꝇ", "Ꝇ"),
                    new("ł̨", "Ł̨"),
                    new("ɫ̨", "Ɫ̨"),
                    new("ĺ", "ĺ"),
                    new("l̆", "L̆"),
                    new("l̂", "L̂"),
                    new("l̦", "L̦"),
                    new("l̈", "L̈"),
                    new("l̇", "L̇"),
                    new("l̋", "L̋"),
                    new("l̏", "L̏"),
                    new("l̀", "L̀"),
                    new("l̉", "L̉"),
                    new("l̑", "L̑"),
                    new("l̄", "L̄"),
                    new("l̨", "L̨"),
                    new("l̊", "L̊"),
                    new("l̥", "L̥"),
                    new("l̰", "L̰"),
                    new("l̥̄", "L̥̄"),
                    new("ł̣", "Ł̣"),
                    new("ꞁ", "Ꞁ"),
                    new(String.Empty, "ʟ"),
                    new("ỻ", "Ỻ"),
                    new("ǉ", "Ǉ"),
                    new(String.Empty, "ǈ"),
                    new("ꞎ", String.Empty),
                    new("ꬷ", String.Empty),
                    new("ꬸ", String.Empty),
                    new("ꬹ", String.Empty),
                    new("ᶅ", String.Empty),
                    new("ɭ", String.Empty),
                    new("ȴ", String.Empty),
                    new("ꝲ", String.Empty),
                    new("𝼄", String.Empty),
                    new("𝼑", String.Empty),
                    new("𝼓", String.Empty),
                    new("𝼦", String.Empty),
                    new("ʪ", String.Empty),
                    new("ʫ", String.Empty),
                    new("ɮ", String.Empty),
                    new("𝼅", String.Empty),
                    new("℔", String.Empty),
                    new(String.Empty, "ᴌ"),
                    new("£", "£"),
                    new("₤", "₤"),
                    new("₺", "₺"),
                    new("₶", "₶"),
                    new("ｌ", "Ｌ"),
                };
            case LetterKey.M:
                return new AccentPair[]
                {
                    new("ḿ", "Ḿ"),
                    new("m̋", "M̋"),
                    new("ṁ", "Ṁ"),
                    new("ṃ", "Ṃ"),
                    new("m̃", "M̃"),
                    new("ɱ", "Ɱ"),
                    new("m̆", "M̆"),
                    new("m̌", "M̌"),
                    new("m̧", "M̧"),
                    new("m̂", "M̂"),
                    new("m̭", "M̭"),
                    new("m̦", "M̦"),
                    new("m̈", "M̈"),
                    new("m̏", "M̏"),
                    new("m̀", "M̀"),
                    new("m̉", "M̉"),
                    new("m̑", "M̑"),
                    new("m̄", "M̄"),
                    new("m̱", "M̱"),
                    new("m̨", "M̨"),
                    new("m̊", "M̊"),
                    new("m̥", "M̥"),
                    new("m̰", "M̰"),
                    new("ɯ", "Ɯ"),
                    new("ᵯ", String.Empty),
                    new("ᶆ", String.Empty),
                    new("ꬺ", String.Empty),
                    new("ɰ", String.Empty),
                    new("ꝳ", String.Empty),
                    new("ꟺ", String.Empty),
                    new("ꟽ", String.Empty),
                    new(String.Empty, "ᴍ"),
                    new(String.Empty, "ᴟ"),
                    new("₼", "₼"),
                    new("₥", "₥"),
                    new("ℳ", "ℳ"),
                    new("🆭", "🆭"),
                    new("ｍ", "Ｍ"),
                };
            case LetterKey.N:
                return new AccentPair[]
                {
                    new("ñ", "Ñ"),
                    new("ń", "Ń"),
                    new("ṉ", "Ṉ"),
                    new("ŋ", "Ŋ"),
                    new("ǹ", "Ǹ"),
                    new("ň", "Ň"),
                    new("ṅ", "Ṅ"),
                    new("ņ", "Ņ"),
                    new("ṇ", "Ṇ"),
                    new("ṋ", "Ṋ"),
                    new("n̈", "N̈"),
                    new("ɲ", "Ɲ"),
                    new("ƞ", "Ƞ"),
                    new("n̨", "N̨"),
                    new("ꞑ", "Ꞑ"),
                    new("ꞥ", "Ꞥ"),
                    new("n̆", "N̆"),
                    new("n̂", "N̂"),
                    new("n̦", "N̦"),
                    new("n̋", "N̋"),
                    new("n̏", "N̏"),
                    new("n̉", "N̉"),
                    new("n̑", "N̑"),
                    new("n̄", "N̄"),
                    new("n̊", "N̊"),
                    new("n̥", "N̥"),
                    new("n̰", "N̰"),
                    new("𝼇", String.Empty),
                    new("𝼔", String.Empty),
                    new("𝼧", String.Empty),
                    new("ǌ", "Ǌ"),
                    new(String.Empty, "ǋ"),
                    new("ᵰ", String.Empty),
                    new("ᶇ", String.Empty),
                    new("ɳ", String.Empty),
                    new("ȵ", String.Empty),
                    new("ꬻ", String.Empty),
                    new("ꬼ", String.Empty),
                    new("ꝴ", String.Empty),
                    new(String.Empty, "ɴ"),
                    new(String.Empty, "ᴎ"),
                    new("₦", "₦"),
                    new("№", "№"),
                    new("ｎ", "Ｎ"),
                };
            case LetterKey.O:
                return new AccentPair[]
                {
                    new("ô", "Ô"),
                    new("ö", "Ö"),
                    new("ó", "Ó"),
                    new("ò", "Ò"),
                    new("õ", "Õ"),
                    new("ō", "Ō"),
                    new("ø", "Ø"),
                    new("ŏ", "Ŏ"),
                    new("ố", "Ố"),
                    new("ồ", "Ồ"),
                    new("ỗ", "Ỗ"),
                    new("ổ", "Ổ"),
                    new("ǒ", "Ǒ"),
                    new("ȫ", "Ȫ"),
                    new("ő", "Ő"),
                    new("ṍ", "Ṍ"),
                    new("ṏ", "Ṏ"),
                    new("ȭ", "Ȭ"),
                    new("ȯ", "Ȯ"),
                    new("o͘", "O͘"),
                    new("ȱ", "Ȱ"),
                    new("ǿ", "Ǿ"),
                    new("ǫ", "Ǫ"),
                    new("ǭ", "Ǭ"),
                    new("ṓ", "Ṓ"),
                    new("ṑ", "Ṑ"),
                    new("ỏ", "Ỏ"),
                    new("ȍ", "Ȍ"),
                    new("ȏ", "Ȏ"),
                    new("ơ", "Ơ"),
                    new("ớ", "Ớ"),
                    new("ờ", "Ờ"),
                    new("ỡ", "Ỡ"),
                    new("ở", "Ở"),
                    new("ợ", "Ợ"),
                    new("ọ", "Ọ"),
                    new("ộ", "Ộ"),
                    new("o̩", "O̩"),
                    new("ò̩", "Ò̩"),
                    new("ó̩", "Ó̩"),
                    new("ǫ̈", "Ǫ̈"),
                    new("ǫ́", "Ǫ́"),
                    new("o̧", "O̧"),
                    new("ø̨", "Ø̨"),
                    new("o̭", "O̭"),
                    new("o̦", "O̦"),
                    new("o̱", "O̱"),
                    new("o̊", "O̊"),
                    new("o̥", "O̥"),
                    new("o̰", "O̰"),
                    new("ō̂", "Ō̂"),
                    new("ō̃", "Ō̃"),
                    new("ō̈", "Ō̈"),
                    new("ø̄", "Ø̄"),
                    new("ō̊", "Ō̊"),
                    new("ɵ", "Ɵ"),
                    new("ꝋ", "Ꝋ"),
                    new("ꝍ", "Ꝍ"),
                    new("ɔ", "Ɔ"),
                    new("ɔ́", "Ɔ́"),
                    new("ɔ̧", "Ɔ̧"),
                    new("ɔ̀", "Ɔ̀"),
                    new("ꝯ", "Ꝯ"),
                    new("ꟁ", "Ꟁ"),
                    new("ꬽ", String.Empty),
                    new("ꬾ", String.Empty),
                    new("𝼛", String.Empty),
                    new("ꬿ", String.Empty),
                    new("œ", "Œ"),
                    new("œ̆", "Œ̆"),
                    new("œ̄", "Œ̄"),
                    new(String.Empty, "ɶ"),
                    new("ꞝ", "Ꞝ"),
                    new(String.Empty, "ʘ"),
                    new(String.Empty, "ᴏ"),
                    new(String.Empty, "ᴐ"),
                    new(String.Empty, "ᴑ"),
                    new(String.Empty, "ᴒ"),
                    new(String.Empty, "ᴓ"),
                    new("ꭀ", String.Empty),
                    new("ꭁ", String.Empty),
                    new("ꭂ", String.Empty),
                    new("ᴔ", String.Empty),
                    new("ꭢ", String.Empty),
                    new("ⱺ", String.Empty),
                    new("ꭃ", String.Empty),
                    new("ꭄ", String.Empty),
                    new("ᴕ", String.Empty),
                    new("ᴖ", String.Empty),
                    new("ᴗ", String.Empty),
                    new("ᶗ", String.Empty),
                    new("ꝏ", "Ꝏ"),
                    new("ｏ", "Ｏ"),
                };
            case LetterKey.P:
                return new AccentPair[]
                {
                    new("ṕ", "Ṕ"),
                    new("ṗ", "Ṗ"),
                    new("ᵽ", "Ᵽ"),
                    new("ƥ", "Ƥ"),
                    new("p̃", "P̃"),
                    new("ꝑ", "Ꝑ"),
                    new("ꝓ", "Ꝓ"),
                    new("ꝕ", "Ꝕ"),
                    new("p̆", "P̆"),
                    new("p̌", "P̌"),
                    new("p̧", "P̧"),
                    new("p̂", "P̂"),
                    new("p̭", "P̭"),
                    new("p̦", "P̦"),
                    new("p̈", "P̈"),
                    new("p̣", "P̣"),
                    new("p̋", "P̋"),
                    new("p̏", "P̏"),
                    new("p̀", "P̀"),
                    new("p̉", "P̉"),
                    new("p̑", "P̑"),
                    new("p̄", "P̄"),
                    new("p̱", "P̱"),
                    new("p̨", "P̨"),
                    new("p̊", "P̊"),
                    new("p̥", "P̥"),
                    new("p̰", "P̰"),
                    new("ᵱ", String.Empty),
                    new("ᶈ", String.Empty),
                    new(String.Empty, "ꟼ"),
                    new(String.Empty, "ᴘ"),
                    new("₱", "₱"),
                    new("₧", "₧"),
                    new("₰", "₰"),
                    new("℗", "℗"),
                    new("🄯", "🄯"),
                    new("ｐ", "Ｐ"),
                };
            case LetterKey.Q:
                return new AccentPair[]
                {
                    new("ꝗ", "Ꝗ"),
                    new("ꝙ", "Ꝙ"),
                    new("ɋ", "Ɋ"),
                    new("q̃", "Q̃"),
                    new("q́", "Q́"),
                    new("q̆", "Q̆"),
                    new("q̌", "Q̌"),
                    new("q̧", "Q̧"),
                    new("q̂", "Q̂"),
                    new("q̭", "Q̭"),
                    new("q̦", "Q̦"),
                    new("q̈", "Q̈"),
                    new("q̇", "Q̇"),
                    new("q̣", "Q̣"),
                    new("q̋", "Q̋"),
                    new("q̏", "Q̏"),
                    new("q̀", "Q̀"),
                    new("q̉", "Q̉"),
                    new("q̑", "Q̑"),
                    new("q̄", "Q̄"),
                    new("q̱", "Q̱"),
                    new("q̨", "Q̨"),
                    new("q̊", "Q̊"),
                    new("q̥", "Q̥"),
                    new("q̰", "Q̰"),
                    new("q̣̈", "Q̣̈"),
                    new("q̣̇", "Q̣̇"),
                    new("q̣̈", "Q̣̈"),
                    new("ȹ", String.Empty),
                    new("ʠ", String.Empty),
                    new(String.Empty, "ꞯ"),
                    new("ｑ", "Ｑ"),
                };
            case LetterKey.R:
                return new AccentPair[]
                {
                    new("ř", "Ř"),
                    new("ṛ", "Ṛ"),
                    new("ṟ", "Ṟ"),
                    new("ṝ", "Ṝ"),
                    new("ŕ", "Ŕ"),
                    new("ṙ", "Ṙ"),
                    new("ŗ", "Ŗ"),
                    new("ȑ", "Ȑ"),
                    new("ȓ", "Ȓ"),
                    new("r̃", "R̃"),
                    new("ɍ", "Ɍ"),
                    new("ꞧ", "Ꞧ"),
                    new("ɽ", "Ɽ"),
                    new("ꝵ", "ꝶ"),
                    new("ꝛ", "Ꝛ"),
                    new("ꝝ", "Ꝝ"),
                    new("ꞃ", "Ꞃ"),
                    new("r̆", "R̆"),
                    new("r̂", "R̂"),
                    new("r̭", "R̭"),
                    new("r̦", "R̦"),
                    new("r̈", "R̈"),
                    new("r̋", "R̋"),
                    new("r̀", "R̀"),
                    new("r̉", "R̉"),
                    new("r̄", "R̄"),
                    new("r̨", "R̨"),
                    new("r̊", "R̊"),
                    new("r̥", "R̥"),
                    new("r̰", "R̰"),
                    new("r̥̄", "R̥̄"),
                    new("ʀ", "Ʀ"),
                    new("ꞟ", "Ꞟ"),
                    new("ᵲ", String.Empty),
                    new("ꭈ", String.Empty),
                    new("ꭉ", String.Empty),
                    new("ꭊ", String.Empty),
                    new("ꭨ", String.Empty),
                    new(String.Empty, "ꭆ"),
                    new("ꭇ", String.Empty),
                    new(String.Empty, "℟"),
                    new(String.Empty, "℞"),
                    new("ɼ", String.Empty),
                    new("ᵳ", String.Empty),
                    new("ᶉ", String.Empty),
                    new("ɿ", String.Empty),
                    new("ʅ", String.Empty),
                    new("ⱹ", String.Empty),
                    new("ꭅ", String.Empty),
                    new("ꭋ", String.Empty),
                    new("ꭌ", String.Empty),
                    new("𝼈", String.Empty),
                    new("𝼕", String.Empty),
                    new("𝼖", String.Empty),
                    new("𝼨", String.Empty),
                    new("ɹ", String.Empty),
                    new("ɺ", String.Empty),
                    new("ɻ", String.Empty),
                    new("ɾ", String.Empty),
                    new(String.Empty, "ʁ"),
                    new(String.Empty, "ᴙ"), 
                    new(String.Empty, "ᴚ"), 
                    new("₹", "₹"),
                    new("₨", "₨"),
                    new("®", "®"),
                    new("ｒ", "Ｒ"),
                };
            case LetterKey.S:
                return new AccentPair[]
                {
                    new("š", "Š"),
                    new("ß", "ẞ"),
                    new("ś", "Ś"),
                    new("ş", "Ş"),
                    new("ṣ", "Ṣ"),
                    new("ṥ", "Ṥ"),
                    new("ŝ", "Ŝ"),
                    new("ṧ", "Ṧ"),
                    new("s̈", "S̈"),
                    new("ṡ", "Ṡ"),
                    new("ṩ", "Ṩ"),
                    new("ș", "Ș"),
                    new("s̩", "S̩"),
                    new("ṡ̃", "Ṡ̃"),
                    new("s̨", "S̨"),
                    new("ꞅ", "Ꞅ"),
                    new("ꞩ", "Ꞩ"),
                    new("ꟊ", "Ꟊ"),
                    new("ȿ", "Ȿ"),
                    new("ʂ", "Ʂ"),
                    new("ƨ", "Ƨ"),
                    new("ꝭ", "Ꝭ"),
                    new("ꟙ", "Ꟙ"),
                    new("s̆", "S̆"),
                    new("s̭", "S̭"),
                    new("s̋", "S̋"),
                    new("s̏", "S̏"),
                    new("s̀", "S̀"),
                    new("s̉", "S̉"),
                    new("s̑", "S̑"),
                    new("s̄", "S̄"),
                    new("s̱", "S̱"),
                    new("s̊", "S̊"),
                    new("s̥", "S̥"),
                    new("s̃", "S̃"),
                    new("s̰", "S̰"),
                    new("ʃ", "Ʃ"),
                    new("ꟗ", "Ꟗ"),
                    new("ꭍ", String.Empty),
                    new("ᶋ", String.Empty),
                    new("ᶘ", String.Empty),
                    new("𝼋", String.Empty),
                    new("𝼌", String.Empty),
                    new("ᶊ", String.Empty),
                    new("ᵴ", String.Empty),
                    new("𝼞", String.Empty),
                    new("𝼩", String.Empty),
                    new("ƪ", String.Empty),
                    new("ʆ", String.Empty),
                    new("ſ", String.Empty),
                    new("ẜ", String.Empty),
                    new("ẝ", String.Empty),
                    new("ẛ", String.Empty),
                    new(String.Empty, "ꜱ"),
                    new("ﬆ", String.Empty),
                    new("ﬅ", String.Empty),
                    new("ᴤ", String.Empty),
                    new("$", "$"),
                    new("₷", "₷"),
                    new("§", "§"),
                    new("ｓ", "Ｓ"),
                };
            case LetterKey.T:
                return new AccentPair[]
                {
                    new("ṭ", "Ṭ"),
                    new("ť", "Ť"),
                    new("ṫ", "Ṫ"),
                    new("ţ", "Ţ"),
                    new("ț", "Ț"),
                    new("ṱ", "Ṱ"),
                    new("ṯ", "Ṯ"),
                    new("ŧ", "Ŧ"),
                    new("ⱦ", "Ⱦ"),
                    new("ƭ", "Ƭ"),
                    new("ʈ", "Ʈ"),
                    new("ẗ", "T̈"),
                    new("ꞇ", "Ꞇ"),
                    new("ʇ", "Ʇ"),
                    new("þ", "Þ"),
                    new("ꝥ", "Ꝥ"),
                    new("ꝧ", "Ꝧ"),
                    new("t́", "T́"),
                    new("t̆", "T̆"),
                    new("t̂", "T̂"),
                    new("t̏", "T̏"),
                    new("t̀", "T̀"),
                    new("t̉", "T̉"),
                    new("t̑", "T̑"),
                    new("t̄", "T̄"),
                    new("t̨", "T̨"),
                    new("t̊", "T̊"),
                    new("t̥", "T̥"),
                    new("t̃", "T̃"),
                    new("t̰", "T̰"),
                    new("ꜩ", "Ꜩ"),
                    new("ȶ", String.Empty),
                    new("ᵵ", "T̴"),
                    new("ƫ", String.Empty),
                    new("ʦ", String.Empty),
                    new("ꭧ", String.Empty),
                    new("ʧ", String.Empty),
                    new("𝼗", String.Empty),
                    new("𝼜", String.Empty),
                    new("ʨ", String.Empty),
                    new("ƾ", String.Empty),
                    new("þ", String.Empty),
                    new("𝼉", String.Empty),
                    new("𝼍", String.Empty),
                    new("𝼪", String.Empty),
                    new("ᵺ", String.Empty),
                    new("ꝷ", String.Empty),
                    new(String.Empty, "ᴛ"),
                    new("₮", "₮"),
                    new("₸", "₸"),
                    new("™", "™"),
                    new("ｔ", "Ｔ"),
                };
            case LetterKey.U:
                return new AccentPair[]
                {
                    new("û", "Û"),
                    new("ù", "Ù"),
                    new("ü", "Ü"),
                    new("ú", "Ú"),
                    new("ū", "Ū"),
                    new("ṷ", "Ṷ"),
                    new("ŭ", "Ŭ"),
                    new("ǔ", "Ǔ"),
                    new("ů", "Ů"),
                    new("ǘ", "Ǘ"),
                    new("ǜ", "Ǜ"),
                    new("ǚ", "Ǚ"),
                    new("ǖ", "Ǖ"),
                    new("ű", "Ű"),
                    new("ũ", "Ũ"),
                    new("ṹ", "Ṹ"),
                    new("ų", "Ų"),
                    new("ų́", "Ų́"),
                    new("ų̃", "Ų̃"),
                    new("ṻ", "Ṻ"),
                    new("ū̀", "Ū̀"),
                    new("ū́", "Ū́"),
                    new("ū̃", "Ū̃"),
                    new("ủ", "Ủ"),
                    new("ȕ", "Ȕ"),
                    new("ȗ", "Ȗ"),
                    new("ư", "Ư"),
                    new("ứ", "Ứ"),
                    new("ừ", "Ừ"),
                    new("ữ", "Ữ"),
                    new("ử", "Ử"),
                    new("ự", "Ự"),
                    new("ụ", "Ụ"),
                    new("ṳ", "Ṳ"),
                    new("ṵ", "Ṵ"),
                    new("u̇", "U̇"),
                    new("u̇̄", "U̇̄"),
                    new("ʉ", "Ʉ"),
                    new("ꞹ", "Ꞹ"),
                    new("ꞿ", "Ꞿ"),
                    new("u̧", "U̧"),
                    new("u̦", "U̦"),
                    new("u̱", "U̱"),
                    new("u̥", "U̥"),
                    new("ū̂", "Ū̂"),
                    new("ṳ̄", "Ṳ̄"),
                    new("ů́", "Ů́"),
                    new("ů̃", "Ů̃"),
                    new("ũ̊", "Ũ̊"),
                    new("ᶙ", String.Empty),
                    new("ꭐ", String.Empty),
                    new("ꭑ", String.Empty),
                    new("ꭏ", String.Empty),
                    new("ꭎ", String.Empty),
                    new("ꭒ", String.Empty),
                    new("ᵫ", String.Empty),
                    new("ꭣ", String.Empty),
                    new(String.Empty, "ᴝ"),
                    new(String.Empty, "ᴞ"),
                    new(String.Empty, "ᵾ"),
                    new("ꝸ", String.Empty),
                    new("ｕ", "Ｕ"),
                };
            case LetterKey.V:
                return new AccentPair[]
                {
                    new("ṽ", "Ṽ"),
                    new("ṿ", "Ṿ"),
                    new("v̇", "V̇"),
                    new("ṿ", "Ṿ"),
                    new("ꝟ", "Ꝟ"),
                    new("ʋ", "Ʋ"),
                    new("ỽ", "Ỽ"),
                    new("ʌ", "Ʌ"),
                    new("v́", "V́"),
                    new("v̆", "V̆"),
                    new("v̌", "V̌"),
                    new("v̧", "V̧"),
                    new("v̂", "V̂"),
                    new("v̭", "V̭"),
                    new("v̦", "V̦"),
                    new("v̈", "V̈"),
                    new("v̋", "V̋"),
                    new("v̏", "V̏"),
                    new("v̀", "V̀"),
                    new("v̉", "V̉"),
                    new("v̑", "V̑"),
                    new("v̄", "V̄"),
                    new("v̱", "V̱"),
                    new("v̨", "V̨"),
                    new("v̊", "V̊"),
                    new("v̥", "V̥"),
                    new("v̰", "V̰"),
                    new("ʌ", "Ʌ"),
                    new("ʌ́", "Ʌ́"),
                    new("ʌ̀", "Ʌ̀"),
                    new("ᶌ", String.Empty),
                    new("ⱱ", String.Empty),
                    new("ⱴ", String.Empty),
                    new(String.Empty, "ᴠ"),
                    new("ꝡ", "Ꝡ"),
                    new("ꝩ", "Ꝩ"),
                    new(String.Empty, "℣"),
                    new("ｖ", "Ｖ"),
                };
            case LetterKey.W:
                return new AccentPair[]
                {
                    new("ŵ", "Ŵ"),
                    new("ẃ", "Ẃ"),
                    new("ẁ", "Ẁ"),
                    new("ẅ", "Ẅ"),
                    new("ẇ", "Ẇ"),
                    new("ẉ", "Ẉ"),
                    new("ꟃ", "Ꟃ"),
                    new("ẘ", "W̊"),
                    new("ⱳ", "Ⱳ"),
                    new("w̆", "W̆"),
                    new("w̌", "W̌"),
                    new("w̧", "W̧"),
                    new("w̭", "W̭"),
                    new("w̦", "W̦"),
                    new("w̋", "W̋"),
                    new("w̏", "W̏"),
                    new("w̉", "W̉"),
                    new("w̑", "W̑"),
                    new("w̄", "W̄"),
                    new("w̱", "W̱"),
                    new("w̨", "W̨"),
                    new("w̥", "W̥"),
                    new("w̃", "W̃"),
                    new("w̰", "W̰"),
                    new("ƿ", "Ƿ"),
                    new("ʍ", String.Empty),
                    new("ɰ", String.Empty),
                    new(String.Empty, "ᴡ"),
                    new("ʬ", "ʬ"),
                    new("₩", "₩"),
                    new("ｗ", "Ｗ"),
                };
            case LetterKey.X:
                return new AccentPair[]
                {
                    new("ẍ", "Ẍ"),
                    new("x́", "X́"),
                    new("x̂", "X̂"),
                    new("x̌", "X̌"),
                    new("ẋ", "Ẋ"),
                    new("x̧", "X̧"),
                    new("x̱", "X̱"),
                    new("x̣", "X̣"),
                    new("x́", "X́"),
                    new("x̆", "X̆"),
                    new("x̭", "X̭"),
                    new("x̦", "X̦"),
                    new("x̋", "X̋"),
                    new("x̏", "X̏"),
                    new("x̀", "X̀"),
                    new("x̉", "X̉"),
                    new("x̑", "X̑"),
                    new("x̄", "X̄"),
                    new("x̨", "X̨"),
                    new("x̊", "X̊"),
                    new("x̥", "X̥"),
                    new("x̃", "X̃"),
                    new("x̰", "X̰"),
                    new("ᶍ", String.Empty),
                    new("ꭖ", String.Empty),
                    new("ꭗ", String.Empty),
                    new("ꭘ", String.Empty),
                    new("ꭙ", String.Empty),
                    new("ｘ", "Ｘ"),
                };
            case LetterKey.Y:
                return new AccentPair[]
                {
                    new("ÿ", "Ÿ"),
                    new("ý", "Ý"),
                    new("ȳ", "Ȳ"),
                    new("ŷ", "Ŷ"),
                    new("ỳ", "Ỳ"),
                    new("ẙ", "Y̊"),
                    new("ỹ", "Ỹ"),
                    new("ẏ", "Ẏ"),
                    new("ỷ", "Ỷ"),
                    new("ỵ", "Ỵ"),
                    new("y̨", "Y̨"),
                    new("ɏ", "Ɏ"),
                    new("ƴ", "Ƴ"),
                    new("ỿ", "Ỿ"),
                    new("y̆", "Y̆"),
                    new("y̌", "Y̌"),
                    new("y̧", "Y̧"),
                    new("y̭", "Y̭"),
                    new("y̦", "Y̦"),
                    new("y̋", "Y̋"),
                    new("y̏", "Y̏"),
                    new("y̑", "Y̑"),
                    new("y̱", "Y̱"),
                    new("y̥", "Y̥"),
                    new("y̰", "Y̰"),
                    new("ȳ́", "Ȳ́"),
                    new("ȳ̀", "Ȳ̀"),
                    new("ȳ̃", "Ȳ̃"),
                    new("ꭚ", String.Empty),
                    new("𝼆", String.Empty),
                    new("ʎ", String.Empty),
                    new("ʏ", String.Empty),
                    new("¥", "¥"),
                    new("ｙ", "Ｙ"),
                };
            case LetterKey.Z:
                return new AccentPair[]
                {
                    new("ž", "Ž"),
                    new("ẕ", "Ẕ"),
                    new("ż", "Ż"),
                    new("ź", "Ź"),
                    new("ẑ", "Ẑ"),
                    new("ẓ", "Ẓ"),
                    new("ƶ", "Ƶ"),
                    new("ȥ", "Ȥ"),
                    new("ⱬ", "Ⱬ"),
                    new("z̨", "Z̨"),
                    new("ɀ", "Ɀ"),
                    new("ᶎ", "Ᶎ"),
                    new("ʒ", "Ʒ"),
                    new("ƹ", "Ƹ"),
                    new("ǯ", "Ǯ"),
                    new("ꝣ", "Ꝣ"),
                    new("ȝ", "Ȝ"),
                    new("z̆", "Z̆"),
                    new("z̧", "Z̧"),
                    new("z̭", "Z̭"),
                    new("z̦", "Z̦"),
                    new("z̈", "Z̈"),
                    new("z̋", "Z̋"),
                    new("z̏", "Z̏"),
                    new("z̀", "Z̀"),
                    new("z̉", "Z̉"),
                    new("z̑", "Z̑"),
                    new("z̄", "Z̄"),
                    new("z̊", "Z̊"),
                    new("z̥", "Z̥"),
                    new("z̃", "Z̃"),
                    new("z̰", "Z̰"),
                    new("𝼘", String.Empty),
                    new("ᵶ", String.Empty),
                    new("ʐ", String.Empty),
                    new("ʑ", String.Empty),
                    new("ƺ", String.Empty),
                    new("ʓ", String.Empty),
                    new("ᶚ", String.Empty),
                    new(String.Empty, "ᴢ"),
                    new(String.Empty, "ᴣ"),
                    new("ｚ", "Ｚ"),
                };
            case LetterKey.Currency:
                return new AccentPair[]
                {
                    new("$", "$"),
                    new("¢", "¢"),
                    new("£", "£"),
                    new("¤", "¤"),
                    new("¥", "¥"),
                    new("֏", "֏"),
                    new("؋", "؋"),
                    new("߾", "߾"),
                    new("߿", "߿"),
                    new("৲", "৲"),
                    new("৳", "৳"),
                    new("৹", "৹"),
                    new("৻", "৻"),
                    new("૱", "૱"),
                    new("௹", "௹"),
                    new("රු", "රු"),
                    new("฿", "฿"),
                    new("៛", "៛"),
                    new("₠", "₠"),
                    new("₡", "₡"),
                    new("₢", "₢"),
                    new("₣", "₣"),
                    new("₤", "₤"),
                    new("₥", "₥"),
                    new("₦", "₦"),
                    new("₧", "₧"),
                    new("₨", "₨"),
                    new("₩", "₩"),
                    new("₪", "₪"),
                    new("₫", "₫"),
                    new("€", "€"),
                    new("₭", "₭"),
                    new("₮", "₮"),
                    new("₯", "₯"),
                    new("₰", "₰"),
                    new("₱", "₱"),
                    new("₲", "₲"),
                    new("₳", "₳"),
                    new("₴", "₴"),
                    new("₵", "₵"),
                    new("₶", "₶"),
                    new("₷", "₷"),
                    new("₸", "₸"),
                    new("₹", "₹"),
                    new("₺", "₺"),
                    new("₻", "₻"),
                    new("₼", "₼"),
                    new("₽", "₽"),
                    new("₾", "₾"),
                    new("₿", "₿"),
                    new("꠸", "꠸"),
                    new("﷼", "﷼"),
                    new("﹩", "﹩"),
                    new("＄", "＄"),
                    new("￠", "￠"),
                    new("￡", "￡"),
                    new("￥", "￥"),
                    new("￦", "￦"),
                    new("ƒ", "ƒ"),
                    new("元", "元"),
                    new("円", "円"),
                    new("圆", "圆"),
                    new("圓", "圓"),
                    new("원", "원"),
                    new("ރ", "ރ"),
                    new("रु", "रु"),
                    new("ರ", "ರ"),
                    new("𑿝", "𑿝"),
                    new("𑿞", "𑿞"),
                    new("𑿟", "𑿟"),
                    new("𑿠", "𑿠"),
                    new("𞋿", "𞋿"),
                    new("𞲰", "𞲰"),
                    new("⃀", "⃀"),
                    new("𐆚", "𐆚"),
                    new("𐆖", "𐆖"),
                    new("𐆙", "𐆙"),
                    new("𐆗", "𐆗"),
                    new("𐆘", "𐆘"),
                };
            case LetterKey.Exclamation:
                return new AccentPair[]
                {
                    new("¡", "¡"),
                    new("‼", "‼"),
                    new("⁉", "⁉"),
                    new("！", "！"),
                    new("﹗", "﹗"),
                    new("︕", "︕"),
                    new("𝼊", "𝼊"),
                };
            case LetterKey.Question:
                return new AccentPair[]
                {
                    new("¿", "¿"),
                    new("⁇", "⁇"),
                    new("⁈", "⁈"),
                    new("？", "？"),
                    new("﹖", "﹖"),
                    new("⸮", "⸮"),
                    new("︖", "︖"),
                };
            case LetterKey.Num_0:
                return new AccentPair[]
                {
                    new("０", "０"),
                };
            case LetterKey.Num_1:
                return new AccentPair[]
                {
                    new("１", "１"), 
                };
            case LetterKey.Num_2:
                return new AccentPair[]
                {
                    new("２", "２"),
                };
            case LetterKey.Num_3:
                return new AccentPair[]
                {
                    new("３", "３"),
                };
            case LetterKey.Num_4:
                return new AccentPair[]
                {
                    new("４", "４"),
                };
            case LetterKey.Num_5:
                return new AccentPair[]
                {
                    new("５", "５"),
                };
            case LetterKey.Num_6:
                return new AccentPair[]
                {
                    new("６", "６"),
                };
            case LetterKey.Num_7:
                return new AccentPair[]
                {
                    new("７", "７"),
                };
            case LetterKey.Num_8:
                return new AccentPair[]
                {
                    new("８", "８"),
                };
            case LetterKey.Num_9:
                return new AccentPair[]
                {
                    new("９", "９"),
                };
        }

        throw new ArgumentException("Letter {0} is missing", letter.ToString());
    }
}

public record AccentPair(string lower, string upper);

public enum Position
{
    Top,
    Bottom,
    Left,
    Right,
    TopLeft,
    TopRight,
    BottomLeft,
    BottomRight,
    Center,
}
